# Generated by Django 3.1.4 on 2021-01-20 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('displayImage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myimage',
            old_name='hotel_Main_Img',
            new_name='Main_Img',
        ),
    ]
