# Generated by Django 3.1.4 on 2021-01-22 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('displayImage', '0002_auto_20210120_1012'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyPdf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Main_pdf', models.FileField(null=True, upload_to='files/', verbose_name='')),
            ],
        ),
        migrations.DeleteModel(
            name='Gallery',
        ),
    ]
