# Generated by Django 3.1.4 on 2021-01-27 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('displayImage', '0003_auto_20210122_1326'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileFieldModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='mypdf',
            name='Main_pdf',
            field=models.FileField(upload_to='files/'),
        ),
    ]
