# Generated by Django 3.1.4 on 2021-02-01 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('displayImage', '0004_auto_20210127_0156'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileFieldModel',
        ),
    ]
